---
- name: Add Docker repository key
  become: True
  apt_key:
    data: "{{ lookup('file', 'files/docker.gpg') }}"
    state: present

- name: Remove old docker repo
  become: True
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo debian-{{ ansible_distribution_release }} main"
    mode: "0644"
    state: absent

- name: Remove old docker repository key
  become: True
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: absent

- name: Add docker APT repo
  become: True
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    mode: "0644"
    state: present

- name: Add docker group
  become: True
  group:
    name: docker
    state: present

- name: Install docker packages
  become: True
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Install docker-compose
  when: docker_install_compose | bool
  apt:
    name:
      - docker-compose
    state: present
    update_cache: yes
    cache_valid_time: 1800 

