---
- name: Add docker group
  become: True
  group:
    name: docker
    state: present

- name: Add docker_users to the docker group
  become: True
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"

- name: Install docker packages
  become: True
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Install docker-compose
  when: docker_install_compose | bool
  apt:
    name:
      - docker-compose
      - gnupg2
      - pass
    state: present
    update_cache: yes
    cache_valid_time: 1800 
